---
- name: Copy network configuration on the host
  copy: src=spinalstack.xml
        dest=/tmp/spinalstack.xml

- name: determine if libvirt network spinalstack is present
  shell: "virsh net-list | grep spinalstack"
  register: spinalstack_net
  ignore_errors: true

- name: Copy network configuration on the host
  copy: src=spinalstack.xml
        dest=/tmp/spinalstack.xml
  when: spinalstack_net.rc == 1

- name: Configure the network
  command: virsh net-create /tmp/spinalstack.xml
  when: spinalstack_net.rc == 1

- name: Configure the different domains
  virt: name={{ item }}
        command=define
        uri=qemu:///system
        xml="{{ lookup('file',  item + '.xml') }}"
  with_items: nodes
  
- name: Start the domains
  virt: name={{ item }}
        state=running
        uri=qemu:///system
  with_items: nodes

- name: Copy XML device snippet
  copy: src=libvirt/{{ item }}.xml
        dest=/tmp
  with_items:
    - openstack1-ceph41
    - openstack1-ceph42
    - openstack1-ceph43
    - openstack1-ceph44
    - openstack2-ceph41
    - openstack2-ceph42
    - openstack2-ceph43
    - openstack2-ceph44
    - openstack3-ceph41
    - openstack3-ceph42
    - openstack3-ceph43
    - openstack3-ceph44

- name: Load the disks openstack1
  command: virsh attach-device openstack1 /tmp/{{ item }}.xml
  with_items:
    - openstack1-ceph41
    - openstack1-ceph42
    - openstack1-ceph43
    - openstack1-ceph44

- name: Load the disks openstack2
  command: virsh attach-device openstack2 /tmp/{{ item }}.xml
  with_items:
    - openstack2-ceph41
    - openstack2-ceph42
    - openstack2-ceph43
    - openstack2-ceph44

- name: Load the disks openstack3
  command: virsh attach-device openstack3 /tmp/{{ item }}.xml
  with_items:
    - openstack3-ceph41
    - openstack3-ceph42
    - openstack3-ceph43
    - openstack3-ceph44

- name: Wait for server to restart
  local_action:
    module: wait_for
     host={{ item }}
     port=22
     delay=1
     timeout=3000
  with_items: nodes
